data:
  backend: native
  type: image_folder
  workers: 8
  nb_classes: 102
  train_dir: datasets/oxford-102-flowers/mod_train
  val_dir: datasets/oxford-102-flowers/mod_test
  augmentation:
      type: bit
  oversampling: true
optim:
    type: SGD_AGC
    momentum: 0.9
    base_lr: 0.001
    batch: 128
    batch_split: 32
    weight_decay: 0

logging:
    eval_every: 100
