data:
  backend: native
  type: pets
  workers: 8
  nb_classes: 37
  train_dir: datasets/oxford-iiit-pet/
  val_dir: datasets/oxford-iiit-pet/
  augmentation:
      type: bit
optim:
    type: SGD_AGC
    momentum: 0.9
    base_lr: 0.001
    batch: 128
    batch_split: 32
    weight_decay: 0

logging:
    eval_every: 100
