data:
    backend: threads
    type: lmdb
    workers: 16
    train_dir: "datasets/imagenet-1K/lmdb/train"
    val_dir: "datasets/imagenet-1K/lmdb/valid"
    nb_classes: 1000
    augmentation:
        type: random_resized_crop
        rand_augment:
            N: 2
            M: 9
    image_size: 224

mixed_precision:
    enabled: true
    backend: native

seed: 42

optim:
    type: SGD_AGC
    momentum: 0.9
    base_lr: 0.03
    base_batch_size: 256
    train_local_batch_size: 32
    val_local_batch_size: 256
    epochs: 120
    warmup_epochs: 15
    weight_decay: 0.0001
    gradient_accumulate: 1
    lr_scheduler:
        type: cosine

model:
    type: BiT-S-R50x1


logging:
    save_checkpoint: true
    validate: true

horovod:
    fp16_allreduce: false
